config/routes.rb
Rails.application.routes.draw do
  constraints subdomain: 'blazer' do
    mount Blazer::Engine => '/'
  end

  constraints subdomain: 'pghero' do
    mount PgHero::Engine => '/'
  end

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  constraints subdomain: 'sidekiq' do
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      # Protect against timing attacks:
      # - See https://codahale.com/a-lesson-in-timing-attacks/
      # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV.fetch("SIDEKIQ_USERNAME"))) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV.fetch("SIDEKIQ_PASSWORD")))
    end if Rails.env.production?
    mount Sidekiq::Web => '/'
  end

  devise_scope :user do
    patch '/verification', to: 'users/confirmations#update', as: :update_user_confirmation
  end
  devise_for :users,
    path: '',
    path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', confirmation: 'verification' },
    controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations',
                   omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }

  resources :author_profiles, only: %i[index show create update], path: 'authors'

  # HTML+AMP routes
  scope defaults: { format: 'html' }, constraints: lambda { |req| req.format == :html || req.format == :amp } do
    resources :coin_articles, only: %i[index show], path: 'how-to-buy-cryptocurrency'
  end

  # HTML only routes
  scope defaults: { format: 'html' }, constraints: { format: 'html' } do
    get '/calculators/:id', to: 'calculators#show', as: 'calculator'
    get '/coins/:id_or_slug', to: 'coins#show', as: 'coin'
    resources :coins, only: %i[index]
    resources :contributor_submissions, path: 'contributor-submissions'
    get '/cryptocurrency-exchanges/best-(:slug)-exchanges', to: 'exchange_categories#show', as: 'exchange_category'
    get '/cryptocurrency-exchanges/(:slug)-review', to: 'exchange_reviews#show', as: 'exchange_review'
    # get '/cryptocurrency-exchanges/(:slug)', to: 'cmc_exchanges#show', as: 'exchange'
    get '/indicators', to: 'indicators#show', as: 'indicators'
    # get '/icos', to: redirect('/icos/upcoming'), as: 'icos_root'
    # get '/icos(/:status)', to: 'icos#index', as: 'icos'
    get '/news/beta', to: static('/news-beta.html')
    get '/news/:id/:slug', to: 'news#show', as: 'news_item'
    get '/news/:coin_slug', to: 'news#coin_index', as: 'news_coin'
    get '/news', to: 'news#index'
    get '/podcast', to: redirect('https://www.coinfi.com/research/coinfi-podcast', status: 302), as: 'podcast'
    get '/profile', to: 'users#edit'
    put '/profile', to: 'users#update'
    # get '/token-metrics(/:metric_type_slug)', to: 'token_metrics#index', as: 'token_metrics'
  end

  get '/static/:type/:id', to: 'static#show', format: 'png'

  namespace :admin do
    resources :coins do
      get 'influencers', on: :collection
    end
    resources :news_items do
      get 'pending', on: :collection
      get 'tagged', on: :collection
    end
    resources :coin_articles
    resources :authors
    resources :cmc_exchanges
    resources :exchange_reviews
    resources :exchange_categories
    resources :exchange_review_categorizations
    resources :articles
    resources :users
    resources :submission_categories
    resources :contributor_submissions
    resources :countries
    resources :influencers
    resources :trading_signal_triggers
    get 'reddit' => 'articles#reddit'
    root to: 'coins#index'
  end

  namespace :api, constraints: { format: 'json' } do
    get '/coins/search', to: 'coins#search'
    get '/coins/search_by_params', to: 'coins#search_by_params'
    get '/coins/:id/news', to: 'coins#news'
    get '/coins/by-slug/:slug', to: 'coins#by_slug'
    get '/coins/prices', to: 'coins#prices'
    get '/coins/markets', to: 'coins#markets'
    resources :coins, only: %i[index show toplist watchlist dominance] do
      get 'toplist', on: :collection
      get 'watchlist', on: :collection
      get 'dominance', on: :collection
    end
    # get '/token-metrics(/:metric_type_slug)', to: 'token_metrics#index'
    get '/indicators/tickers', to: 'indicators#tickers'
    get '/indicators/overview/:tickers', to: 'indicators#overview'

    resources :currency, only: %i[index]

    namespace :signals do
      resources :coins, only: %i[show], param: :coin_key
      resources :trading_signal_triggers, only: %i[index show create]
      resources :trading_signals, only: %i[show create]
      resources :trading_signal_notifications, only: %i[show create]
      resources :signals_telegram_users, only: %i[index show], param: :telegram_id_or_username do
        get 'for_trading_signal_notifications', on: :collection
        post 'register', on: :collection

        resources :signals_telegram_subscriptions, param: :coin_symbol, only: %i[index show create destroy]
      end
    end

    namespace :watchlist do
      resources :coins, only: %i[index create destroy]
    end

    resources :news, only: %i[index show] do
      resources :news_vote, :path => 'vote', only: %i[index create]
    end
    namespace :newsfeed do
      resources :coins, only: %i[index]
    end

    get '/social_feeds/tweets_by_user', to: 'social_feeds#tweets_by_user'

    get '/user', to: 'user#show'
    patch '/user', to: 'user#update'
  end

  namespace :webhooks do
    post "#{ENV.fetch('SUPERFEEDR_CALLBACK_URL_SEGMENT_SECRET')}-superfeedr-ingest", to: 'websubs#superfeedr_ingest'
  end

  root to: 'home#index'
  get '/about', to: 'pages#show', id: 'about', as: 'page_about'
  get '/press', to: 'pages#show', id: 'press', as: 'page_press'
  get '/contact-us', to: 'pages#show', id: 'contact-us', as: 'page_contact_us'
  get '/ambassadors', to: 'pages#show', id: 'ambassadors', as: 'page_ambassadors'
  get '/win-cofi', to: 'pages#show', id: 'win-cofi', as: 'page_win_cofi'
  get '/privacy-policy', to: 'pages#show', id: 'privacy-policy', as: 'page_privacy'
  get '/unstake', to: 'pages#show', id: 'unstake', as: 'page_unstake'
  get '/signals', to: 'signals#index'
  get '/signals/reservation', to: redirect('/signals')
  patch '/signals/reservation', to: redirect('/signals')

  match '/404', :to => 'errors#not_found', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all
end

app/models/contributor_submission.rb
class ContributorSubmission < ApplicationRecord
  belongs_to :user
  #belongs_to :submission_category

  enum status: {pending: 0, approved: 1, declined: 2}
end

app/controllers/admin/contributor_submissions_controller.rb
module Admin
  class ContributorSubmissionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Coin.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Coin.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/contributor_submissions_controller.rb
class ContributorSubmissionsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_contributor_submission, only: [:show, :edit, :update, :destroy]

  # GET /contributor_submissions
  # GET /contributor_submissions.json
  def index
    @contributor_submissions = current_user.contributor_submissions
  end

  # GET /contributor_submissions/1
  # GET /contributor_submissions/1.json
  def show
  end

  # GET /contributor_submissions/new
  def new
    @contributor_submission = current_user.contributor_submissions.build
  end

  # GET /contributor_submissions/1/edit
  def edit
  end

  # POST /contributor_submissions
  # POST /contributor_submissions.json
  def create
    @contributor_submission = current_user.contributor_submissions.build(contributor_submission_params)

    respond_to do |format|
      if @contributor_submission.save
        format.html { redirect_to contributor_submissions_path, notice: 'Contributor submission was successfully created.' }
        format.json { render :show, status: :created, location: @contributor_submission }
      else
        format.html { render :new }
        format.json { render json: @contributor_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributor_submissions/1
  # PATCH/PUT /contributor_submissions/1.json
  def update
    respond_to do |format|
      if @contributor_submission.update(contributor_submission_params)
        format.html { redirect_to @contributor_submission, notice: 'Contributor submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @contributor_submission }
      else
        format.html { render :edit }
        format.json { render json: @contributor_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributor_submissions/1
  # DELETE /contributor_submissions/1.json
  def destroy
    @contributor_submission.destroy
    respond_to do |format|
      format.html { redirect_to contributor_submissions_url, notice: 'Contributor submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contributor_submission
      @contributor_submission = current_user.contributor_submissions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contributor_submission_params
      params.require(:contributor_submission).permit(:user_id, :title, :summary, :content, :submission_category_id, :status, :disclosure)
    end
end

app/helpers/contributor_submissions_helper.rb
module ContributorSubmissionsHelper
end

app/views/contributor_submissions/_form.html.slim
= simple_form_for @contributor_submission do |f|
  = render partial: 'components/errors', locals: {model: @contributor_submission}
  .field
    = f.input :title
  .field
    = f.label :summary, title: 'Summarize your article’s key points in bullet points', class: 'has-tooltip' do
      ' Summary
      span.text-info
        i.fa.fa-info-circle
    = f.text_area :summary, class: 'form-control'
  .field
    = f.label :content, title: 'Please include links in parenthesis', class: 'has-tooltip' do
      ' Content
      span.text-info
        i.fa.fa-info-circle
    = f.text_area :content, class: 'form-control', rows: 20
  /= f.input :submission_category_id, collection: SubmissionCategory.order(:name), label: 'Category'
  .field
    = f.label :disclosure, title: 'Disclose any positions over $500 USD you hold in any cryptocurrencies mentioned', class: 'has-tooltip' do
      ' Disclosure
      span.text-info
        i.fa.fa-info-circle
    = f.text_area :disclosure, class: 'form-control'

  .actions = f.submit 'Submit Content', class: 'btn btn-blue'

app/views/contributor_submissions/edit.html.slim
.phr.pv3
  .container
    h1 Editing Submission
    = render 'form'

app/views/contributor_submissions/index.html.slim
.phr.pv3
  .container
    .flex.justify-between.flex-wrap.mb4
      .flex-none
        h1.mv0 Your Content Submissions
      .flex-none
        = link_to 'New Content Submission', new_contributor_submission_path, class: 'btn btn-green'

    table.striped
      thead
        tr
          th Title
          th Submission Date
          th Status
          th

      tbody
        - @contributor_submissions.each do |contributor_submission|
          tr
            td = contributor_submission.title
            td = contributor_submission.created_at
            td = contributor_submission.status
            td.tr
              = link_to 'View', contributor_submission, class: 'btn btn-xs btn-white'
              =< link_to 'Edit', edit_contributor_submission_path(contributor_submission), class: 'btn btn-xs btn-white'

app/views/contributor_submissions/new.html.slim
.container.pv3
  .row
    .col-lg-12
      h1 New Content Submission
      .alert.alert-warning.mb4
        | Please ensure that your content meets CoinFi’s <a href="https://www.coinfi.com/blog/editorial-guidelines/" target="_blank">editorial standards</a>.
        br
        | Find details of how CoinFi <a href="https://www.coinfi.com/blog/contributor-compensation/" target="_blank">compensates contributors here</a>.
    .col-lg-6
      == render 'form'
    .col-lg-6
      h3 What are we looking for?
      p While the vision for the CoinFi ecosystem will encompass a wide range of research and analysis, we’re going to start with a narrower scope.

      p Here are the types of content we’re looking for at the moment:

      p <strong>Actionable Investment Ideas</strong>: Write about a coin, token, crypto asset/project in an actionable way for crypto investors. Macro-economic posts are ok, but we don’t publish articles that are primarily focused on economic theory or politics. Explicit buy/sell recommendations are not what we’re looking for, but your piece should help a reader make an investment decision.

      p <strong>Fundamental Analysis</strong>: We value rigorous fundamental analysis. Examine the underlying business model, technology, codebase, competitive environment, team, valuation, or other aspects of a coin, token or other crypto asset. We value well-presented, thoroughly researched pieces that offer an informed viewpoint.

      p <strong>Personal Experience</strong>: Focus is on actionable info, research, analysis, and data, but talking about personal experience is fine in the context of explaining what made you decide to buy or sell a coin for your portfolio. We value insights into why crypto investors made the decisions they did - it is up to readers to evaluate your reasoning for themselves. But providing research and reasoning to support your decision will make your personal experience more valuable.

      p <strong>Quantitative Analysis</strong>: We like numbers and data.  If you have a thesis for how traditional quantitative factors such as price, volume, value, momentum, yield, quality, size influence a coin’s performance which is backed up by hard data, that is interesting to us.  We also like analysis that looks at factors that you think might be pertinent to crypto investing such as sentiment, influencer impact, community growth momentum, advisor impact, etc.

      p A note on Technical Analysis: While TA can be used to support your quantitative analysis, at the moment we don’t accept pure Technical Analysis pieces - defined as analysis based solely on chart patterns.
p

app/views/contributor_submissions/show.html.slim
.phr.pv3
  .container
    p#notice = notice

    .mb4
      strong Title:
      br
      = @contributor_submission.title
    .mb4
      strong Status:
      br
      = @contributor_submission.status
    .mb4
      strong Summary:
      br
      = @contributor_submission.summary
    .mb4
      strong Content:
      br
      = @contributor_submission.content
    .mb4
      strong Disclosure:
      br
      = @contributor_submission.disclosure

    .pt4
      = link_to 'Edit', edit_contributor_submission_path(@contributor_submission), class: 'btn btn-blue'
      =< link_to 'Back', contributor_submissions_path, class: 'btn'